### ISSUE TITLE
S21 ultra - doesn't work currently

### ISSUE THREAD

**Issue by battlesnake** [mueller-ma/Coffee#41] opened 2021-03-12 14:44 UTC
I installed latest from F-droid store today, disabled Battery Optimisation for it, but enabling Coffee has no effect.

 - Samsung Galaxy S21 Ultra
 - Stock firmware
 - No root.
 - No smart unlock

I'm a software engineer, but not familiar with Android.

How can I help with debugging this, or possibly with fixing this?

I should note that in the phone "Settings", the values for "Screen Timeout" go up to 10 minutes but there's no "never" option.  I don't know if the values supported in "settings" place restrictions on what this app can do?

**Comment by mueller-ma** [comment] 2021-03-16 10:43
Coffee holds a wakelock as long as the persistent notification is shown. This has nothing to do with the screen timeout settings of your phone.
To me this seems like a duplicate of #16: Apps are seen as "in foreground" when they have a foreground service running (the persistent notification) by the unmodified AOSP. When an app is moved to background, its wakelocks are stopped.

**Closed by mueller-ma** 2021-03-16 10:43 UTC
Labels: bug

**Comment by battlesnake** [comment] 2021-03-16 12:28
Ah ok, so I need to keep the coffee app in the foreground in order for it to work?  I was hoping it would be like the LineageOS "caffeine" feature where I can have any app open in the foreground.

**Comment by mueller-ma** [comment] 2021-03-17 07:26
Well, it's exactly like caffeine of LineageOS, but Samsung has implemented a custom battery saver which kills the wakelocks hold by Coffee. The app is working fine on AOSP devices or devices without a custom battery saver.
