### ISSUE TITLE
Cannot activate Coffee on Xiaomi Mi 9 with MIUI12 (Android 10)

### ISSUE THREAD

**Issue by natrius** [mueller-ma/Coffee#19] opened 2020-12-06 10:39 UTC
**Describe the bug**

It is in the drop-down menu but i am not able to activate Coffee. 

**Expected behavior**
Drop down the menu, press the "Coffee" button an the symbol appears on top 

**Device (please complete the following information):**
 - Device: Xiaomi Mi9
 - Android version: Android 10 with MIUI 12.0.5 (EU-ROM)

**Additional context**
Coffee 1.2 (F-Droid)

Permission: Permanent notification (no other permissions)
Battery saver: No restrictions
Fullscreen mode: allowed
Autostart: deactivated

**Comment by mueller-ma** [comment] 2020-12-06 17:12
Duplicate of #16 ?

**Comment by natrius** [comment] 2020-12-10 09:59
I read that at first and i don't think so. If i press the tile i put in the drawer nothing happens. No notification, the tile does not change, nothing. I read through https://dontkillmyapp.com/xiaomi and allowed autostart. Fromt he permissions available

1. Homescreen shortcuts
2. show on lock sreen
3. display pop-up windows while running in the background
4. permanent notification

Just 4. is allowed. Notification are allowed. "Battery saver" is set to "No restrictions". Fullscreen Mode is allowed as well.

**Comment by mueller-ma** [comment] 2020-12-10 12:33
Can you capture a ADB log?

**Comment by mueller-ma** [comment] 2020-12-10 12:50
Can you try to remove the tile and re-add it?

**Comment by natrius** [comment] 2020-12-10 13:15
I can, any preferred way on how i should get or what i should do?

I did and no change. I noticed right now it is greyed out, i added a screenshot. 

![signal-2020-12-10-140653](https://user-images.githubusercontent.com/7243447/101776459-3e332280-3af1-11eb-801e-3f99cabced65.jpeg)

**Comment by mueller-ma** [comment] 2020-12-10 13:32
Tiles can have three states: Active (like NFC), inactive (like Battery saver) and disabled (like Coffee in this case). I added a commit that should make sure that the tile is never disabled.

Can you please test the following apk?

- Rename it to .apk
- Uninstall Coffee
- Install my apk

[app-debug.zip](https://github.com/mueller-ma/Coffee/files/5673069/app-debug.zip)

**Comment by natrius** [comment] 2020-12-10 14:01
Lucky i got all states in one screen by coincidence. And, it works with the "active" fix. You can close this ticket, if you want :)

**Comment by mueller-ma** [comment] 2020-12-10 14:27
This fix will ship with Version 1.5.

**Closed by mueller-ma** 2020-12-10 14:27 UTC
Labels: bug

**Comment by natrius** [comment] 2022-05-03 09:23
It did not work btw., i just stuck with changing the screen-on-time. But i kept it installed, just in case and i saw https://github.com/mueller-ma/Coffee/issues/16#issuecomment-1114286938 this popping up and i just want to tell you - its working now for me as well. Running for 5 Minutes now and going.

**Comment by mueller-ma** [comment] 2022-05-03 09:30
Which version did you try?

**Comment by natrius** [comment] 2022-05-03 09:31
I just noticed this is the wrong issue, sorry about that. Should i create a new one, use the other one i mentioned or just stay?

Unsing 2.0 from F-Droid from 30.04.2022

**Comment by mueller-ma** [comment] 2022-05-03 17:57
You can open a new issue, but wait until 2.1 is released on F-Droid first: https://github.com/mueller-ma/Coffee/releases/tag/2.1
2.0 doesn't implement the alternate mode.
