### ISSUE TITLE
Not keeping the display awake in a Xiaomi Mi9 Lite (Android 10)

### ISSUE THREAD

**Issue by LukasThyWalls** [mueller-ma/Coffee#40] opened 2021-03-01 13:03 UTC
**Describe the bug**
Simply, Coffee is not keeping the display awake in my Xiaomi Mi9 Lite. It doesn't matter how i toggled it. I tried to disable the battery settings for the app, and read dontkillmyapp.com tips, but nothing changes.
It only keeps the display on when the the app is open, but you can't do something else than see the app.

**To Reproduce**
* It's only to toggle on Coffee (the notification is there), and wait. The display goes off like if i didn't toggle on Coffee. When i switch on the display again, the Coffee notification is gone.
* If i have Coffee app in display (is open) and toggle on, the display is keep on until i go to home screen, then i wait a few seconds and the display goes off like Coffee isn't doing anything (the Coffee notification is there).

**Expected behavior**
Coffee keeping the display on when the notification is there.

**Device (please complete the following information):**
 - Device: Xiaomi Mi 9 Lite
 - Android version: Android 10 (MIUI 12.0.5)
 - Coffee 1.8 (From F-Droid)

**Additional context**
Here is a logcat (filtered with "coffee" keyword). I did two things meanwhile in the time of the log: open Coffee, toggle on, going to home screen and wait. The screen goes off. After that, i opened again Coffee, toggle on again, and wait for a minute or two in the app itself. It kept the display on, but then i went to the home screen and the display went off in some seconds.

<details>
  <summary>Logcat from Coffee 1.8</summary>
  
  ## Logcat, generated with Logs app (filtered with "Coffee" keyword)
````
03-01 12:54:02.063 D/miuix_anim( 2532): AnimRunningInfo, begin scaleX, toTag = myDown, target object = com.miui.home.launcher.AppIcon{6b661bc VFE...CL. ........ 439,931-642,1241}(Coffee)
03-01 12:54:02.063 D/miuix_anim( 2532): AnimRunningInfo, begin scaleY, toTag = myDown, target object = com.miui.home.launcher.AppIcon{6b661bc VFE...CL. ........ 439,931-642,1241}(Coffee)
03-01 12:54:02.156 D/miuix_anim( 2532): AnimRunningInfo, begin scaleX, toTag = myUp, target object = com.miui.home.launcher.AppIcon{6b661bc VFE...CL. ...P.... 439,931-642,1241}(Coffee)
03-01 12:54:02.156 D/miuix_anim( 2532): AnimRunningInfo, begin scaleY, toTag = myUp, target object = com.miui.home.launcher.AppIcon{6b661bc VFE...CL. ...P.... 439,931-642,1241}(Coffee)
03-01 12:54:02.164 W/XSpaceManagerService( 1658): checkXSpaceControl, from:com.miui.home, to:com.github.muellerma.coffee, with act:android.intent.action.MAIN, callingUserId:0, toUserId:0
03-01 12:54:02.167 I/ActivityTaskManager( 1658): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.github.muellerma.coffee/.MainActivity bnds=[469,1175][622,1328] (has extras)} from uid 10057
03-01 12:54:02.227 D/Boost   ( 1658): hostingType=activity, hostingName={com.github.muellerma.coffee/com.github.muellerma.coffee.MainActivity}, callerPackage=com.miui.home, isSystem=true, isBoostNeeded=false.
03-01 12:54:02.227 D/OemNetd (  658): setPidForPackage: packageName=com.github.muellerma.coffee, pid=32594, pid=10399
03-01 12:54:02.227 I/ActivityManager( 1658): Start proc 32594:com.github.muellerma.coffee/u0a399 for activity {com.github.muellerma.coffee/com.github.muellerma.coffee.MainActivity} caller=com.miui.home
03-01 12:54:02.254 I/GST     (10265): forePkg: com.github.muellerma.coffee, preForePkg: com.miui.home
03-01 12:54:02.253 I/ProcessMonitor( 4533): onForegroundInfoChanged: ForegroundInfo{mForegroundPackageName='com.github.muellerma.coffee', mForegroundUid=10399, mForegroundPid=32594, mLastForegroundPackageName='com.miui.home', mLastForegroundUid=10057, mLastForegroundPid=2532, mMultiWindowForegroundPackageName='null', mMultiWindowForegroundUid=-1, mFlags=1}
03-01 12:54:02.254 I/GameBoosterService( 4533): onForegroundInfoChanged: Cur=com.github.muellerma.coffee	 last=com.miui.home
03-01 12:54:02.262 D/GameBoosterService( 4533): onGameStatusChange foreground:ForegroundInfo{mForegroundPackageName='com.github.muellerma.coffee', mForegroundUid=10399, mForegroundPid=32594, mLastForegroundPackageName='com.miui.home', mLastForegroundUid=10057, mLastForegroundPid=2532, mMultiWindowForegroundPackageName='null', mMultiWindowForegroundUid=-1, mFlags=1}
03-01 12:54:02.300 W/uellerma.coffee(32594): type=1400 audit(0.0:55143): avc: denied { read } for name="u:object_r:vendor_displayfeature_prop:s0" dev="tmpfs" ino=20953 scontext=u:r:untrusted_app:s0:c143,c257,c512,c768 tcontext=u:object_r:vendor_displayfeature_prop:s0 tclass=file permissive=0
03-01 12:54:02.311 E/Perf    (32594): Fail to get file list com.github.muellerma.coffee
03-01 12:54:02.335 D/ForceDarkHelper(32594): updateByCheckExcludeList: pkg: com.github.muellerma.coffee activity: com.github.muellerma.coffee.MainActivity@ae464ea
03-01 12:54:02.344 I/chatty  (32594): uid=10399(com.github.muellerma.coffee) identical 7 lines
03-01 12:54:02.345 D/ForceDarkHelper(32594): updateByCheckExcludeList: pkg: com.github.muellerma.coffee activity: com.github.muellerma.coffee.MainActivity@ae464ea
03-01 12:54:02.351 D/ForceDarkHelper(32594): updateByCheckExcludeList: pkg: com.github.muellerma.coffee activity: com.github.muellerma.coffee.MainActivity@ae464ea
03-01 12:54:02.353 I/chatty  (32594): uid=10399(com.github.muellerma.coffee) identical 3 lines
03-01 12:54:02.354 D/ForceDarkHelper(32594): updateByCheckExcludeList: pkg: com.github.muellerma.coffee activity: com.github.muellerma.coffee.MainActivity@ae464ea
03-01 12:54:02.359 D/Launcher.Model( 2532): LauncherAppsCallback onShortcutsChanged|com.github.muellerma.coffee|UserHandle{0}
03-01 12:54:02.374 D/RecentsImpl( 2532): mActivityStateObserver com.github.muellerma.coffee.MainActivity
03-01 12:54:02.405 D/com.jarsilio.android.autoautorotate (AppLaunchDetectionService$a)(31180): com.github.muellerma.coffee in foreground: deactivating auto-rotate (if not already the case)
03-01 12:54:02.447 I/ActivityTaskManager( 1658): Displayed com.github.muellerma.coffee/.MainActivity: +277ms
03-01 12:54:02.754 I/Timeline( 1658): Timeline: Activity_windows_visible id: ActivityRecord{30930d8 u0 com.github.muellerma.coffee/.MainActivity t1137} time:122979748
03-01 12:54:02.764 E/Layer   (  905): [Surface(name=AppWindowToken{2b30f16 token=Token{6dbcc31 ActivityRecord{30930d8 u0 com.github.muellerma.coffee/.MainActivity t1137}}})/@0x3645c52 - animation-leash#0] No local sync point found
03-01 12:54:04.317 D/CoffeeTile(32594): requestTileStateUpdate()
03-01 12:54:04.321 D/TileServices( 2166): Couldn't find tile for ComponentInfo{com.github.muellerma.coffee/com.github.muellerma.coffee.CoffeeTile}
03-01 12:54:04.325 D/CoffeeTile(32594): requestTileStateUpdate()
03-01 12:54:04.332 D/TileServices( 2166): Couldn't find tile for ComponentInfo{com.github.muellerma.coffee/com.github.muellerma.coffee.CoffeeTile}
03-01 12:54:04.453 D/SpaceNotificationService( 3219): onNotificationPosted pkgname:com.github.muellerma.coffee userId:0 currentUserId:0 isFloat: false
03-01 12:54:04.456 D/StatusBar( 2166): onNotificationPosted key=0|com.github.muellerma.coffee|1|null|10399 isUpdate=false
03-01 12:54:04.473 D/IconCustomizer( 2166): Generate customized icon for com.github.muellerma.coffee.png
03-01 12:54:04.487 D/StatusBar( 2166): No peeking: unimportant notification: 0|com.github.muellerma.coffee|1|null|10399
03-01 12:54:04.545 D/StatusBar( 2166): No peeking: unimportant notification: 0|com.github.muellerma.coffee|1|null|10399
03-01 12:54:07.328 I/ProcessMonitor( 4533): onForegroundInfoChanged: ForegroundInfo{mForegroundPackageName='com.miui.home', mForegroundUid=10057, mForegroundPid=2532, mLastForegroundPackageName='com.github.muellerma.coffee', mLastForegroundUid=10399, mLastForegroundPid=32594, mMultiWindowForegroundPackageName='null', mMultiWindowForegroundUid=-1, mFlags=0}
03-01 12:54:07.328 I/GameBoosterService( 4533): onForegroundInfoChanged: Cur=com.miui.home	 last=com.github.muellerma.coffee
03-01 12:54:07.328 I/GST     (10265): forePkg: com.miui.home, preForePkg: com.github.muellerma.coffee
03-01 12:54:07.329 D/GameBoosterService( 4533): onGameStatusChange foreground:ForegroundInfo{mForegroundPackageName='com.miui.home', mForegroundUid=10057, mForegroundPid=2532, mLastForegroundPackageName='com.github.muellerma.coffee', mLastForegroundUid=10399, mLastForegroundPid=32594, mMultiWindowForegroundPackageName='null', mMultiWindowForegroundUid=-1, mFlags=0}
03-01 12:54:08.947 W/RecentsModel( 2532): getTaskInfoIgnoreHomeAndFreeform   taskInfo=ComponentInfo{com.github.muellerma.coffee/com.github.muellerma.coffee.MainActivity}
03-01 12:54:24.993 D/PowerManagerService( 1658): screen wakeLock:[SCREEN_BRIGHT_WAKE_LOCK        'Coffee::ForegroundService' DISABLED (uid=10399 pid=32594)] disabled
03-01 12:54:31.244 D/CoffeeTile(32594): requestTileStateUpdate()
03-01 12:54:31.246 D/StatusBar( 2166): onNotificationRemoved key=0|com.github.muellerma.coffee|1|null|10399 reason=8
03-01 12:54:31.256 D/StatusBar( 2166): removeNotification StatusBarNotification(pkg=com.github.muellerma.coffee user=UserHandle{0} id=1 tag=null key=0|com.github.muellerma.coffee|1|null|10399: Notification(channel=foreground_service pri=0 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x62 color=0xff4e342e category=service vis=PRIVATE publicVersion=Notification(channel=foreground_service pri=0 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x2 color=0xff4e342e category=service vis=PRIVATE)))
03-01 12:54:31.256 D/StatusBar( 2166):     pkgName=com.github.muellerma.coffee appUid=10399 sdk=30 imp=2 sysApp=F priApp=F hasShown=F float=F keyguard=F peek=F fullscreen=F
03-01 12:54:31.256 D/StatusBar( 2166): update app badge num: com.github.muellerma.coffee/,num=0,isAllowed=false,userId=0
03-01 12:54:31.258 I/Launcher.ApplicationsMessage( 2532): update com.github.muellerma.coffee/ to null
03-01 12:54:31.263 D/TileServices( 2166): Couldn't find tile for ComponentInfo{com.github.muellerma.coffee/com.github.muellerma.coffee.CoffeeTile}
03-01 12:54:32.869 D/miuix_anim( 2532): AnimRunningInfo, begin alpha, toTag = z, target object = com.miui.home.launcher.ShortcutIcon{39a9d47 VFE...CL. ........ 439,1559-642,1848}(Coffee)
03-01 12:54:32.869 D/miuix_anim( 2532): AnimRunningInfo, begin scaleX, toTag = z, target object = com.miui.home.launcher.ShortcutIcon{39a9d47 VFE...CL. ........ 439,1559-642,1848}(Coffee)
03-01 12:54:32.869 D/miuix_anim( 2532): AnimRunningInfo, begin scaleY, toTag = z, target object = com.miui.home.launcher.ShortcutIcon{39a9d47 VFE...CL. ........ 439,1559-642,1848}(Coffee)
03-01 12:54:32.869 D/miuix_anim( 2532): AnimRunningInfo, begin translationY, toTag = z, target object = com.miui.home.launcher.ShortcutIcon{39a9d47 VFE...CL. ........ 439,1559-642,1848}(Coffee)
03-01 12:55:04.314 D/miuix_anim( 2532): AnimRunningInfo, begin alpha, toTag = z, target object = com.miui.home.launcher.ShortcutIcon{39a9d47 VFE...CL. ........ 439,1559-642,1848}(Coffee)
03-01 12:55:04.314 D/miuix_anim( 2532): AnimRunningInfo, begin scaleX, toTag = z, target object = com.miui.home.launcher.ShortcutIcon{39a9d47 VFE...CL. ........ 439,1559-642,1848}(Coffee)
03-01 12:55:04.314 D/miuix_anim( 2532): AnimRunningInfo, begin scaleY, toTag = z, target object = com.miui.home.launcher.ShortcutIcon{39a9d47 VFE...CL. ........ 439,1559-642,1848}(Coffee)
r.ShortcutIcon{39a9d47 VFE...CL. ........ 439,1559-642,1848}(Coffee)
03-01 12:55:08.656 D/Launcher.CellLayout( 2532): touch item:ShortcutInfo, id=195, itemType=0, user=UserHandle{0}, mIconType=0, pkgName=com.github.muellerma.coffee, className=com.github.muellerma.coffee.MainActivity, screenId=1, container=-100, cellX=2, cellY=5, spanX=1, spanY=1, isLandscapePos=false
03-01 12:55:08.658 D/miuix_anim( 2532): AnimRunningInfo, begin scaleX, toTag = myDown, target object = com.miui.home.launcher.ShortcutIcon{39a9d47 VFE...CL. ........ 439,1559-642,1848}(Coffee)
03-01 12:55:08.658 D/miuix_anim( 2532): AnimRunningInfo, begin scaleY, toTag = myDown, target object = com.miui.home.launcher.ShortcutIcon{39a9d47 VFE...CL. ........ 439,1559-642,1848}(Coffee)
03-01 12:55:08.734 D/miuix_anim( 2532): AnimRunningInfo, begin scaleX, toTag = myUp, target object = com.miui.home.launcher.ShortcutIcon{39a9d47 VFE...CL. ...P.... 439,1559-642,1848}(Coffee)
03-01 12:55:08.735 D/miuix_anim( 2532): AnimRunningInfo, begin scaleY, toTag = myUp, target object = com.miui.home.launcher.ShortcutIcon{39a9d47 VFE...CL. ...P.... 439,1559-642,1848}(Coffee)
03-01 12:55:08.741 W/XSpaceManagerService( 1658): checkXSpaceControl, from:com.miui.home, to:com.github.muellerma.coffee, with act:android.intent.action.MAIN, callingUserId:0, toUserId:0
03-01 12:55:08.742 I/ActivityTaskManager( 1658): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.github.muellerma.coffee/.MainActivity bnds=[469,1664][622,1817] (has extras)} from uid 10057
03-01 12:55:08.772 I/ProcessMonitor( 4533): onForegroundInfoChanged: ForegroundInfo{mForegroundPackageName='com.github.muellerma.coffee', mForegroundUid=10399, mForegroundPid=32594, mLastForegroundPackageName='com.miui.home', mLastForegroundUid=10057, mLastForegroundPid=2532, mMultiWindowForegroundPackageName='null', mMultiWindowForegroundUid=-1, mFlags=0}
03-01 12:55:08.772 I/GameBoosterService( 4533): onForegroundInfoChanged: Cur=com.github.muellerma.coffee	 last=com.miui.home
03-01 12:55:08.772 I/GST     (10265): forePkg: com.github.muellerma.coffee, preForePkg: com.miui.home
03-01 12:55:08.785 D/GameBoosterService( 4533): onGameStatusChange foreground:ForegroundInfo{mForegroundPackageName='com.github.muellerma.coffee', mForegroundUid=10399, mForegroundPid=32594, mLastForegroundPackageName='com.miui.home', mLastForegroundUid=10057, mLastForegroundPid=2532, mMultiWindowForegroundPackageName='null', mMultiWindowForegroundUid=-1, mFlags=0}
03-01 12:55:08.794 D/RecentsImpl( 2532): mActivityStateObserver com.github.muellerma.coffee.MainActivity
03-01 12:55:08.814 D/com.jarsilio.android.autoautorotate (AppLaunchDetectionService$a)(31180): com.github.muellerma.coffee in foreground: deactivating auto-rotate (if not already the case)
03-01 12:55:08.850 D/com.jarsilio.android.autoautorotate (AppLaunchDetectionService$a)(31180): com.github.muellerma.coffee in foreground: deactivating auto-rotate (if not already the case)
03-01 12:55:09.274 I/Timeline( 1658): Timeline: Activity_windows_visible id: ActivityRecord{30930d8 u0 com.github.muellerma.coffee/.MainActivity t1137} time:123046268
03-01 12:55:09.288 E/Layer   (  905): [Surface(name=AppWindowToken{2b30f16 token=Token{6dbcc31 ActivityRecord{30930d8 u0 com.github.muellerma.coffee/.MainActivity t1137}}})/@0x3645c52 - animation-leash#0] No local sync point found
03-01 12:55:10.810 D/CoffeeTile(32594): requestTileStateUpdate()
03-01 12:55:10.813 D/TileServices( 2166): Couldn't find tile for ComponentInfo{com.github.muellerma.coffee/com.github.muellerma.coffee.CoffeeTile}
03-01 12:55:10.815 D/CoffeeTile(32594): requestTileStateUpdate()
03-01 12:55:10.834 D/TileServices( 2166): Couldn't find tile for ComponentInfo{com.github.muellerma.coffee/com.github.muellerma.coffee.CoffeeTile}
03-01 12:55:10.963 D/SpaceNotificationService( 3219): onNotificationPosted pkgname:com.github.muellerma.coffee userId:0 currentUserId:0 isFloat: false
03-01 12:55:10.970 D/StatusBar( 2166): onNotificationPosted key=0|com.github.muellerma.coffee|1|null|10399 isUpdate=false
03-01 12:55:10.984 D/IconCustomizer( 2166): Generate customized icon for com.github.muellerma.coffee.png
03-01 12:55:10.998 D/StatusBar( 2166): No peeking: unimportant notification: 0|com.github.muellerma.coffee|1|null|10399
03-01 12:55:11.063 D/StatusBar( 2166): No peeking: unimportant notification: 0|com.github.muellerma.coffee|1|null|10399
03-01 12:55:26.649 D/PowerCheckerService( 6013): foreground, uid = 10399, app = com.github.muellerma.coffee
03-01 12:58:27.424 I/ProcessMonitor( 4533): onForegroundInfoChanged: ForegroundInfo{mForegroundPackageName='com.miui.home', mForegroundUid=10057, mForegroundPid=2532, mLastForegroundPackageName='com.github.muellerma.coffee', mLastForegroundUid=10399, mLastForegroundPid=32594, mMultiWindowForegroundPackageName='null', mMultiWindowForegroundUid=-1, mFlags=0}
03-01 12:58:27.424 I/GameBoosterService( 4533): onForegroundInfoChanged: Cur=com.miui.home	 last=com.github.muellerma.coffee
03-01 12:58:27.424 I/GST     (10265): forePkg: com.miui.home, preForePkg: com.github.muellerma.coffee
03-01 12:58:27.425 D/GameBoosterService( 4533): onGameStatusChange foreground:ForegroundInfo{mForegroundPackageName='com.miui.home', mForegroundUid=10057, mForegroundPid=2532, mLastForegroundPackageName='com.github.muellerma.coffee', mLastForegroundUid=10399, mLastForegroundPid=32594, mMultiWindowForegroundPackageName='null', mMultiWindowForegroundUid=-1, mFlags=0}
03-01 12:58:37.778 D/PowerManagerService( 1658): screen wakeLock:[SCREEN_BRIGHT_WAKE_LOCK        'Coffee::ForegroundService' DISABLED (uid=10399 pid=32594)] disabled
03-01 12:58:44.010 D/StatusBar( 2166): onNotificationRemoved key=0|com.github.muellerma.coffee|1|null|10399 reason=8
03-01 12:58:44.019 D/CoffeeTile(32594): requestTileStateUpdate()
03-01 12:58:44.021 D/StatusBar( 2166): removeNotification StatusBarNotification(pkg=com.github.muellerma.coffee user=UserHandle{0} id=1 tag=null key=0|com.github.muellerma.coffee|1|null|10399: Notification(channel=foreground_service pri=0 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x62 color=0xff4e342e category=service vis=PRIVATE publicVersion=Notification(channel=foreground_service pri=0 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x2 color=0xff4e342e category=service vis=PRIVATE)))
03-01 12:58:44.021 D/StatusBar( 2166):     pkgName=com.github.muellerma.coffee appUid=10399 sdk=30 imp=2 sysApp=F priApp=F hasShown=F float=F keyguard=F peek=F fullscreen=F
03-01 12:58:44.021 D/StatusBar( 2166): update app badge num: com.github.muellerma.coffee/,num=0,isAllowed=false,userId=0
03-01 12:58:44.028 I/Launcher.ApplicationsMessage( 2532): update com.github.muellerma.coffee/ to null
03-01 12:58:44.033 D/TileServices( 2166): Couldn't find tile for ComponentInfo{com.github.muellerma.coffee/com.github.muellerma.coffee.CoffeeTile}
03-01 12:58:47.402 D/miuix_anim( 2532): AnimRunningInfo, begin alpha, toTag = z, target object = com.miui.home.launcher.ShortcutIcon{39a9d47 VFE...CL. ........ 439,1559-642,1848}(Coffee)
03-01 12:58:47.402 D/miuix_anim( 2532): AnimRunningInfo, begin scaleX, toTag = z, target object = com.miui.home.launcher.ShortcutIcon{39a9d47 VFE...CL. ........ 439,1559-642,1848}(Coffee)
03-01 12:58:47.402 D/miuix_anim( 2532): AnimRunningInfo, begin scaleY, toTag = z, target object = com.miui.home.launcher.ShortcutIcon{39a9d47 VFE...CL. ........ 439,1559-642,1848}(Coffee)
03-01 12:58:47.402 D/miuix_anim( 2532): AnimRunningInfo, begin translationY, toTag = z, target object = com.miui.home.launcher.ShortcutIcon{39a9d47 VFE...CL. ........ 439,1559-642,1848}(Coffee)
````

</details>

Thanks!

**Comment by mueller-ma** [comment] 2021-03-08 06:46
The wakelock is killed by the OS when the app goes to background: `screen wakeLock:[SCREEN_BRIGHT_WAKE_LOCK        'Coffee::ForegroundService' DISABLED (uid=10399 pid=32594)] disabled`
To me this seems like a duplicate of #16: Apps are seen as "in foreground" when they have a foreground service running (the persistent notification) by the unmodified AOSP.

**Closed by mueller-ma** 2021-03-08 06:46 UTC
Labels: bug

**Comment by LukasThyWalls** [comment] 2021-03-08 18:32
Thanks for checking it.
