### ISSUE TITLE
There's no icon showing in Android 12 when system theme is set to dark

### ISSUE THREAD

**Issue by d4f5409d** [mueller-ma/Coffee#202] opened 2022-10-28 13:35 UTC
**Describe the bug**
There's no icon showing in Android 12 when system theme is set to dark. We don't have an icon for the dark theme

**To Reproduce**
1. Go to System settings
2. Click on Display and brightness
3. Switch to dark mode
4. See error in the icon launcher ( a white circle is the icon)

**Expected behavior**
The icon should appear as it does in light mode.

**Screenshots**
Light mode: 
![IMG_20221028_153346.jpg](https://user-images.githubusercontent.com/76624594/198613990-b62bdfe2-fd6a-4243-8d89-31484c5dd617.jpg)

Dark mode:
![IMG_20221028_153353.jpg](https://user-images.githubusercontent.com/76624594/198614143-29e6c89f-e8e9-4087-9480-60727ac4179c.jpg)

**Device (please complete the following information):**
 - Device: OnePlus 8
 - Android version: 12

**Additional context**
Seems like others having this issue as well.

**Comment by mueller-ma** [comment] 2022-10-28 16:08
Thanks for filling out the issue template. I try to find a solution.

Duplicate of #183

**Closed by mueller-ma** 2022-10-28 16:08 UTC
Labels: bug
